# phaseshift.yaml
# PhaseShift Open Environmental Control
# Version: 2025.06.26.4
# Developer: @helicopterrun

substitutions:
  device_id:  "phaseshift"
  device_name: "PhaseShift"
  use_fahrenheit: "true"
  temp_unit: "°F"
  default_max_current: "3.5"

  ramp_duration: "5"
  plateau_duration: "5"

  ramp_start_dewpoint: "58.0"
  ramp_end_dewpoint: "51.5"
  ramp_start_temp: "68.0"
  ramp_end_temp: "65.0"
  ramp_start_fan_speed: "100"
  ramp_end_fan_speed: "40"
  ramp_start_fan_modulation: "100"
  ramp_end_fan_modulation: "30"

  plateau_dewpoint: "51.7"
  plateau_temp: "65.0"
  plateau_fan_speed: "10"
  plateau_fan_modulation: "30"

  hold_dewpoint: "52.0"
  hold_temp: "65.0"
  hold_fan_speed: "10"
  hold_fan_modulation: "30"

  # Networking (optional static IP)
  static_ip: "192.168.50.224"
  gateway:   "192.168.50.1"
  subnet:    "255.255.255.0"

  # I²C pins
  i2c_sda: "21"
  i2c_scl: "22"

  # I²C device addresses
  ads1115_address:  "0x49"
  mcp4728_address:  "0x60"

  # TEC driver control pins
  nsleep_a_pin:   "26"
  nsleep_b_pin:   "18"
  p_mode_pin:     "19"

  # TEC PWM outputs & frequency
  pwm_tec_a_pin:  "13"
  pwm_tec_b_pin:  "33"
  pwm_tec_freq:   "19531Hz"

  # Fan PWM outputs & frequency
  pwm_fan_hot_pin:  "32"
  pwm_fan_cold_pin: "25"
  pwm_fan_circ_pin: "17"
  pwm_fan_freq:     "25000Hz"

  # Heater relay pin
  heat_pin:       "12"

  # Heatsink temperature sensor configuration
  dallas_pin:         "27"
  cold_temp_address:  "0x4B"
  hot_temp_address:   "0x48"

  # SNTP timezone
  timezone: "America/Los_Angeles"

packages:
  hardware:  !include packages/hardware_tmp117.yaml
  controls:  !include packages/controls.yaml
  sensors:  !include packages/sensors.yaml
  climate:   !include packages/climate.yaml
  actuators: !include packages/actuators.yaml
  scripts:   !include packages/scripts.yaml
  timing:    !include packages/timing.yaml

esphome:
  name: $device_id
  friendly_name: $device_name
  name_add_mac_suffix: true

  on_boot:
    then:
      - script.execute: ti_driver_startup

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

# —————————————————————————————————————————————————
# Wi-Fi, Logging, API & OTA
# —————————————————————————————————————————————————
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.50.224
    gateway: 192.168.50.1
    subnet: 255.255.255.0

logger:
  level: DEBUG
  logs: 
    template.sensor: WARN
    gpio.output: WARN
    template.number: WARN
    ledc.output: WARN
    switch.gpio: WARN
    tmp117: INFO
    sht3xd: INFO
    text_sensor: NONE
    bme280.sensor: NONE
    ads1115.sensor: INFO

api:
  encryption:
    key: !secret ss2_api
ota:
  - platform: esphome
    password: !secret ss2_ota

globals:
  - id: cycle_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: ramp_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: plateau_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: hold_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: last_mode
    type: std::string
    restore_value: true
    initial_value: '"Hold"'
  - id: ramp_elapsed
    type: uint32_t
    restore_value: yes
    initial_value: '0'
  - id: plateau_elapsed
    type: uint32_t
    restore_value: yes
    initial_value: '0'
  - id: hold_elapsed
    type: uint32_t
    restore_value: yes
    initial_value: '0'
