# phaseshift.yaml
# PhaseShift Open Environmental Control
# Version: 2025.06.29.1
# Developer: @helicopterrun

substitutions:
  device_id:  "phaseshift"
  device_name: "PhaseShift"
  use_fahrenheit: "true"
  temp_unit: "°F"
  default_max_current: "4.5"

  ramp_duration: "8"
  plateau_duration: "4"

  ramp_start_dewpoint: "81.0"
  ramp_end_dewpoint: "69.5.0"
  ramp_start_temp: "85.0"
  ramp_end_temp: "85.0"
  ramp_start_fan_speed: "0"
  ramp_end_fan_speed: "0"
  ramp_start_fan_modulation: "60"
  ramp_end_fan_modulation: "60"

  plateau_dewpoint: "36.0"
  plateau_temp: "41.0"
  plateau_fan_speed: "0"
  plateau_fan_modulation: "60"

  hold_dewpoint: "36.0"
  hold_temp: "41.0"
  hold_fan_speed: "0"
  hold_fan_modulation: "60"

  # I²C pins
  i2c_sda: "21"
  i2c_scl: "22"

  # I²C device addresses
  ads1115_address:  "0x49"
  mcp4728_address:  "0x60"

  # TEC driver control pins
  nsleep_a_pin:   "26"
  nsleep_b_pin:   "18"
  p_mode_pin:     "19"

  # TEC PWM outputs & frequency
  pwm_tec_a_pin:  "13"
  pwm_tec_b_pin:  "33"
  pwm_tec_freq:   "19531Hz"

  # Fan PWM outputs & frequency
  pwm_fan_hot_pin:  "32"
  pwm_fan_cold_pin: "25"
  pwm_fan_circ_pin: "17"
  pwm_fan_freq:     "25000Hz"

  # Heater relay pin
  heat_pin:       "12"

  # Heatsink temperature sensor configuration
  dallas_pin:         "27"
  cold_temp_address:  "0x35482f0087c5a728"
  hot_temp_address:   "0x48759500879e6f28"

  # SNTP timezone
  timezone: "America/Los_Angeles"

packages:
  hardware:  !include packages/hardware_dallas.yaml
  controls:  !include packages/controls.yaml
  sensors:  !include packages/sensors.yaml
  climate:   !include packages/climate.yaml
  actuators: !include packages/actuators.yaml
  scripts:   !include packages/scripts.yaml
  timing:    !include packages/timing.yaml

esphome:
  name: $device_id
  friendly_name: $device_name
  name_add_mac_suffix: true

  on_boot:
    then:
      - script.execute: ti_driver_startup

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

# —————————————————————————————————————————————————
# Wi-Fi, Logging, API & OTA
# —————————————————————————————————————————————————
wifi:
  # Set up a wifi access point
  ap:
    password: "phaseshift"

captive_portal:

esp32_improv:
  authorizer: none

dashboard_import:
  package_import_url: helicopterrun/phaseshift/phaseshift.yaml@2025.06.29.1⁩
  packages: !git "https://github.com/helicopterrun/phaseshift.git@main"
  import_full_config: false # or true

logger:

api:

ota:
  - platform: esphome

globals:
  - id: cycle_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: ramp_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: plateau_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: hold_start_timestamp
    type: uint32_t
    restore_value: true
    initial_value: '0'
  - id: last_mode
    type: std::string
    restore_value: true
    initial_value: '"Hold"'
