i2c:
  id: i2c_bus_main
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  frequency: 400khz
  timeout: 10ms

one_wire:
  - platform: gpio
    id: ow_bus
    pin: ${dallas_pin}

ads1115:
  - address: ${ads1115_address}

mcp4728:
  - id: dac_output
    address: ${mcp4728_address}

sensor:
  - platform: dallas_temp
    name: "Cold Side Temperature"
    id: cold_temp
    one_wire_id: ow_bus
    address: ${cold_temp_address}
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    state_class: measurement
    filters:
      - round: 2
    update_interval: 10s

  - platform: dallas_temp
    name: "Hot Side Temperature"
    id: hot_temp
    one_wire_id: ow_bus
    address: ${hot_temp_address}
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    state_class: measurement
    filters:
      - round: 2
    update_interval: 10s