i2c:
  id: i2c_bus_main
  sda: ${i2c_sda}
  scl: ${i2c_scl}
  frequency: 100kHz

ads1115:
  - address: ${ads1115_address}

mcp4728:
  - id: dac_output
    address: ${mcp4728_address}

sensor:
  - platform: tmp117
    name: "Cold Side Temperature"
    id: cold_temp
    address: ${cold_temp_address}
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    state_class: measurement
    filters:
      - exponential_moving_average:
          alpha: 0.1
          send_every: 1
    update_interval: 1s

  - platform: tmp117
    name: "Hot Side Temperature"
    id: hot_temp
    address: ${hot_temp_address}
    device_class: temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    state_class: measurement
    filters:
      - round: 1
    update_interval: 10s